###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: No1s RPG SRD

# Your name to show in the footer
author: Some Person

# Theme
remote_theme: just-the-docs/just-the-docs

# Markdown
markdown: kramdown


# just-the-docs configs
# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  core:
    permalink: "/core"
    output: true
  characters:
    permalink: "/characters/_characters/""
    output: true
  bamf:
    permalink: "/bamf"
    output: true
  

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    core:
      # Give the collection a name
      name: Core Rules
      nav_fold: true
    characters:
      name: Characters
      nav_fold: true
    bamf:
      name: bamf
      nav_fold: true
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true


# sidebar nav
# sidebar:
#   - label: Core Rules
#     children:
#       - Core Mechanic & Gameplay Loop
#       - Actions & Shifts
#       - Challenge
#       - Initiative
#       - Momentum & Entropy
#       - Hits
#       - Zones
#       - Waypoints
#   - label: Characters
#     children:
#       - characters-traits
#       - characters-skills
#       - characters-trainings
#       - characters-talents
