# Name of website
title: No1s RPG SRD

# Your name to show in the footer
author: Some Person

# Theme
remote_theme: just-the-docs/just-the-docs

# Markdown
markdown: kramdown


# just-the-docs configs
# Define Jekyll collections
# collections:
#   # Define a collection named "tests", its documents reside in the "_tests" directory
#   core:
#     permalink: /:core/:_core
#     output: true
#   characters:
#     permalink: /:characters/:_characters/
#     output: true
#   bamf:
#     permalink: /:bamf/:_bamf
#     output: true
#   training:
#     permalink: /:training/:_training
#     output: true


# just_the_docs:
  # Define which collections are used in just-the-docs
  # collections:
  #   # Reference the "tests" collection
  #   core:
  #     # Give the collection a name
  #     name: Core Rules
  #     nav_fold: true
  #   characters:
  #     name: Characters
  #     nav_fold: true
  #     has_children: true
  #   bamf:
  #     name: bamf
  #     nav_fold: true
  #   training:
  #     name: Training
  #     nav_fold: true
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true


callouts:
  note:
    title: 'Note:'
    color: blue


color_scheme: dark